import dotenv from 'dotenv';
import { RegistryService } from '../src/services/registry';
import { X402Tool, ToolCategory } from '@delivery-shield/shared';

// Load environment variables
dotenv.config();

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017';

/**
 * Seed script to populate the registry with initial tools
 */
async function seedRegistry() {
  const registryService = new RegistryService(MONGODB_URI);
  
  try {
    console.log('Connecting to MongoDB...');
    await registryService.connect();
    
    console.log('Clearing existing tools...');
    const toolsCollection = await registryService.getToolsCollection();
    await toolsCollection.deleteMany({});
    
    console.log('Seeding tools...');
    
    // Tool 1: Midnight Burritos
    const midnightBurritos: X402Tool = {
      name: 'Midnight Burritos',
      version: '1.0.0',
      endpoint: 'https://api.midnightburritos.com/order',
      priceUsdc: 10,
      category: ToolCategory.FOOD,
      reliabilityScore: 0.9
    };
    
    // Tool 2: Rocket Couriers
    const rocketCouriers: X402Tool = {
      name: 'Rocket Couriers',
      version: '1.0.0',
      endpoint: 'https://api.rocketcouriers.com/deliver',
      priceUsdc: 2,
      category: ToolCategory.LOGISTICS,
      reliabilityScore: 0.95
    };
    
    // Tool 3: Shield Verify (Our App)
    const shieldVerify: X402Tool = {
      name: 'Shield Verify',
      version: '1.0.0',
      endpoint: 'https://api.deliveryshield.com/verify',
      priceUsdc: 0,
      category: ToolCategory.RESOLUTION,
      reliabilityScore: 1.0
    };
    
    // Insert tools (without embeddings for now - embeddings would be generated by AI service)
    await registryService.insertTool(midnightBurritos);
    console.log('✓ Inserted: Midnight Burritos (Food, $10 USDC, 0.9 reliability)');
    
    await registryService.insertTool(rocketCouriers);
    console.log('✓ Inserted: Rocket Couriers (Logistics, $2 USDC, 0.95 reliability)');
    
    await registryService.insertTool(shieldVerify);
    console.log('✓ Inserted: Shield Verify (Resolution, $0 USDC, 1.0 reliability)');
    
    // Optionally seed some reputation incidents for demonstration
    console.log('\nSeeding sample reputation incidents...');
    const reputationCollection = await registryService.getReputationCollection();
    await reputationCollection.deleteMany({});
    
    await registryService.insertReputationIncident({
      toolId: 'Midnight Burritos',
      incidentType: 'Cold',
      orderId: 'order-001',
      timestamp: Date.now() - 86400000, // 1 day ago
      severity: 0.3
    });
    
    await registryService.insertReputationIncident({
      toolId: 'Rocket Couriers',
      incidentType: 'Late',
      orderId: 'order-002',
      timestamp: Date.now() - 172800000, // 2 days ago
      severity: 0.2
    });
    
    console.log('✓ Sample reputation incidents inserted');
    
    // Display merchant reputations
    console.log('\n=== Merchant Reputations ===');
    for (const toolName of ['Midnight Burritos', 'Rocket Couriers', 'Shield Verify']) {
      const reputation = await registryService.getMerchantReputation(toolName);
      console.log(`\n${toolName}:`);
      console.log(`  Total Incidents: ${reputation.totalIncidents}`);
      console.log(`  Cold: ${reputation.coldIncidents}, Late: ${reputation.lateIncidents}`);
      console.log(`  Reputation Score: ${reputation.reputationScore.toFixed(2)}`);
    }
    
    console.log('\n✓ Registry seeding completed successfully!');
    console.log('\nNote: Vector search requires embeddings. To enable natural language search,');
    console.log('generate embeddings using an AI service and create the vector index in MongoDB Atlas.');
    
  } catch (error) {
    console.error('Error seeding registry:', error);
    process.exit(1);
  } finally {
    await registryService.disconnect();
    console.log('\nDisconnected from MongoDB');
  }
}

// Run the seed script
seedRegistry();
